In [150]:
import numpy as np
from hmmlearn import hmm
import pandas as pd
import numpy as np
from hmmlearn.base import ConvergenceMonitor

In [127]:
def Normalization(df):
    df.iloc[:,2:]= df.iloc[:,2:].apply(lambda x: ((x-x.mean()) / (x.std())))
    return df

In [128]:
def preprocessing(path):
#    gamma = 0.9
    df = pd.read_csv(path, header=None, delimiter=' ')
    
    #Normalize the data
    df = Normalization(df)
    
    #Drop the columns which has all values as Nan
    df.dropna(axis=1, how='all', inplace=True)
    
#     #Get Rewards for each time step : 0 except last time step where reward is -100
#     df['Counter'] = df.index
#     lastRowIndex = df.groupby(0).last().Counter.tolist()
#     df['reward'] = df['Counter'].apply(lambda x : -100 if x in lastRowIndex else 0 )
#     df.drop(columns=['Counter'],inplace=True)
    
    #Rename columns
    df.rename(columns={0: "machine", 1: "time"}, inplace=True)
    
#     #Calculate Monte Carlo Value for each row
#     df1 = df.groupby('machine').last()[['time']].reset_index()
#     df = pd.merge(df, df1, on = 'machine', how = 'left').rename(columns ={'time_x':'time','time_y':'lastTimeStamp'})
#     #df['MC_Val'] = (gamma ** (df['lastTimeStamp'] - df['time'] )) * (-100)
#     df['MC_Val'] = (df['lastTimeStamp'] - df['time'] )
#     df = df.drop(columns='lastTimeStamp')
    
    return df

In [129]:
df = preprocessing("../CMAPSSData/train_FD001.txt")

In [130]:
df.head()

machine  time         2         3         5         6         7         8  \
0        1     1 -0.315972 -1.372920  0.999976 -1.721684 -0.134252 -0.925914   
1        1     2  0.872701 -1.031695  0.999976 -1.061754  0.211523 -0.643710   
2        1     3 -1.961827  1.015652  0.999976 -0.661797 -0.413156 -0.525940   
3        1     4  0.324083 -0.008022  0.999976 -0.661797 -1.261284 -0.784812   
4        1     5 -0.864590 -0.690471  0.999976 -0.621801 -1.251498 -0.301511   

          9       10  ...        14        15        16        17        18  \
0  0.999976  0.14168  ...  0.999976 -0.266460  0.334254 -1.058865 -0.269065   
1  0.999976  0.14168  ...  0.999976 -0.191578  1.174871 -0.363637 -0.642829   
2  0.999976  0.14168  ...  0.999976 -1.015279  1.364688 -0.919819 -0.551616   
3  0.999976  0.14168  ...  0.999976 -1.539452  1.961255 -0.224592 -0.520163   
4  0.999976  0.14168  ...  0.999976 -0.977838  1.052846 -0.780774 -0.521736   

         19        20        21        24        25  
0 -0.603801  0.999976 -0.781691  1.348460  1.194398  
1 -0.275845  0.999976 -0.781691  1.016503  1.236892  
2 -0.649128  0.999976 -2.073044  0.739873  0.503411  
3 -1.971617  0.999976 -0.781691  0.352590  0.777773  
4 -0.339837  0.999976 -0.136014  0.463242  1.059526  

[5 rows x 23 columns]

In [131]:
X = df.iloc[:,2:]

In [132]:
X

2         3         5         6         7         8         9   \
0     -0.315972 -1.372920  0.999976 -1.721684 -0.134252 -0.925914  0.999976   
1      0.872701 -1.031695  0.999976 -1.061754  0.211523 -0.643710  0.999976   
2     -1.961827  1.015652  0.999976 -0.661797 -0.413156 -0.525940  0.999976   
3      0.324083 -0.008022  0.999976 -0.661797 -1.261284 -0.784812  0.999976   
4     -0.864590 -0.690471  0.999976 -0.621801 -1.251498 -0.301511  0.999976   
...         ...       ...       ...       ...       ...       ...       ...   
20626 -0.178817 -1.031695  0.999976  1.617961  1.216229  2.188322  0.999976   
20627 -0.727436 -1.714145  0.999976  1.717950  2.279651  2.738285  0.999976   
20628  0.186928 -0.008022  0.999976  1.477975  1.946924  2.138325  0.999976   
20629 -0.498845  1.015652  0.999976  1.098016  2.403608  1.955004  0.999976   
20630 -1.458927 -1.714145  0.999976  2.337884  1.607673  2.578295  0.999976   

            10        11        12  ...        14        15        16  \
0      0.14168  1.121113 -0.516326  ...  0.999976 -0.266460  0.334254   
1      0.14168  0.431920 -0.798074  ...  0.999976 -0.191578  1.174871   
2      0.14168  1.008131 -0.234578  ...  0.999976 -1.015279  1.364688   
3      0.14168  1.222798  0.188044  ...  0.999976 -1.539452  1.961255   
4      0.14168  0.714376 -0.516326  ...  0.999976 -0.977838  1.052846   
...        ...       ...       ...  ...       ...       ...       ...   
20626  0.14168 -2.189276  1.315035  ...  0.999976  1.979996 -2.607906   
20627  0.14168 -2.833277  1.878530  ...  0.999976  1.867673 -2.350298   
20628  0.14168 -2.742891  2.019404  ...  0.999976  2.054877 -1.902872   
20629  0.14168 -3.036645  2.160278  ...  0.999976  3.178105 -2.363856   
20630  0.14168 -2.912364  2.301152  ...  0.999976  2.466728 -2.865515   

             17        18        19        20        21        24        25  
0     -1.058865 -0.269065 -0.603801  0.999976 -0.781691  1.348460  1.194398  
1     -0.363637 -0.642829 -0.275845  0.999976 -0.781691  1.016503  1.236892  
2     -0.919819 -0.551616 -0.649128  0.999976 -2.073044  0.739873  0.503411  
3     -0.224592 -0.520163 -1.971617  0.999976 -0.781691  0.352590  0.777773  
4     -0.780774 -0.521736 -0.339837  0.999976 -0.136014  0.463242  1.059526  
...         ...       ...       ...       ...       ...       ...       ...  
20626  2.278227 -0.322534  1.425260  0.999976  2.446692 -1.805129 -2.921042  
20627  1.722045 -0.380198  1.913194  0.999976  1.155339 -2.856326 -1.203735  
20628  2.000136 -0.141680  3.265013  0.999976  3.092369 -2.081760 -3.292402  
20629  1.861090 -0.233942  2.579771  0.999976  1.155339 -2.911652 -2.085021  
20630  2.278227 -0.336688  1.638564  0.999976  1.801015 -2.469043 -2.194027  

[20631 rows x 21 columns]

In [133]:
lengths = df.groupby("machine").size().tolist()

## We have sequence of trajectories (observations) and their lengths. Now we can use Expectation Maximization to estimate the parameters for the HMM

In [135]:
#Character codes: ‘s’ for startprob, ‘t’ for transmat, ‘m’ for means and ‘c’ for covars.

In [170]:
len(X)

20631

In [171]:
sum(lengths)

20631

In [187]:
lr = hmm.GaussianHMM(n_components=4, covariance_type="diag",init_params="cm", params="mt", random_state=42)
lr.startprob_ = np.array([1.0, 0.0, 0.0, 0.0])
lr.transmat_ = np.array([[0.5, 0.5, 0.0, 0.0],[0.0, 0.5, 0.5, 0.0],[0.0, 0.0, 0.5, 0.5],[0.0,0.0,0.0,1.0]])
lr.fit(X, lengths=lengths)
#lr.fit(X[:193])

GaussianHMM(init_params='cm', n_components=4, params='mt', random_state=42)

In [188]:
lr.transmat_

array([[0.98789878, 0.01210122, 0.        , 0.        ],
       [0.        , 0.98815232, 0.01184768, 0.        ],
       [0.        , 0.        , 0.96299289, 0.03700711],
       [0.        , 0.        , 0.        , 1.        ]])

In [190]:
lr.predict(X[194+lengths[1]+1: 194+lengths[1]+2])

array([0])

In [193]:
lr.covars_.shape

(4, 21, 21)

In [194]:
lr.predict_proba(X[:193])

array([[1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 5.24975360e-168, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 1.80610877e-166, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 5.11487070e-164, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 4.51016914e-161, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 2.57065866e-159, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 7.09508866e-156, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 5.34652329e-153, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 4.28928415e-150, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 2.04051681e-147, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 3.73981271e-145, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 3.41359198e-142, 0.00000000e+000,
      

In [196]:
#Now we need to calculate reward for each state estimate using the formula
#Since there is no action: reward = c1 * (4-st), c1=50

#Lets calculate the reward for each state
#Reward for state1 = 50 * (4-1)= 150
#Reward for state2 = 50 * (4-2)= 100
#Reward for state3 = 50 * (4-3)= 50
#Reward for state4 = 50 * (4-4)= 0

In [206]:
dict_rewards = {0:150, 1:100, 2:50, 3:0} #Note that we are using the state index to denote the state. Hence, 0 to 4

In [198]:
#We have sequence of predicted probabilities using the lr.predict_proba. For each step we will calculate the reward using
#the weighted probability of dict_rewards

In [254]:
def cal_reward(states_prob, dict_rewards):
    reward = 0
    for i,prob in enumerate(states_prob):
        reward+= prob * dict_rewards[i]
    #print(reward)
    return reward

In [263]:
rewards = []

In [264]:
start=0
for length in lengths:
    print(start,start+length, length)
    for states_prob in lr.predict_proba(X[start:start+length]):
        rewards.append(cal_reward(states_prob, dict_rewards))
    start += length

0 192 192
192 479 287
479 658 179
658 847 189
847 1116 269
1116 1304 188
1304 1563 259
1563 1713 150
1713 1914 201
1914 2136 222
2136 2376 240
2376 2546 170
2546 2709 163
2709 2889 180
2889 3096 207
3096 3305 209
3305 3581 276
3581 3776 195
3776 3934 158
3934 4168 234
4168 4363 195
4363 4565 202
4565 4733 168
4733 4880 147
4880 5110 230
5110 5309 199
5309 5465 156
5465 5630 165
5630 5793 163
5793 5987 194
5987 6221 234
6221 6412 191
6412 6612 200
6612 6807 195
6807 6988 181
6988 7146 158
7146 7316 170
7316 7510 194
7510 7638 128
7638 7826 188
7826 8042 216
8042 8238 196
8238 8445 207
8445 8637 192
8637 8795 158
8795 9051 256
9051 9265 214
9265 9496 231
9496 9711 215
9711 9909 198
9909 10122 213
10122 10335 213
10335 10530 195
10530 10787 257
10787 10980 193
10980 11255 275
11255 11392 137
11392 11539 147
11539 11770 231
11770 11942 172
11942 12127 185
12127 12307 180
12307 12481 174
12481 12764 283
12764 12917 153
12917 13119 202
13119 13432 313
13432 13631 199
13631 13993 362
13993 14

In [265]:
len(rewards)

20631

In [266]:
print(len(X), len(rewards), sum(lengths))

20631 20631 20631


In [267]:
lengths[-1]

200

In [268]:
lr.predict_proba(X[-200:])

array([[1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 9.51796468e-057, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 2.55785073e-054, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 6.50299103e-054, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 2.13857941e-053, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 9.01835868e-052, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 2.54748603e-049, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 1.12724504e-048, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 3.66090056e-048, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 1.50291039e-047, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 6.86684481e-046, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 1.16531672e-043, 0.00000000e+000,
      

In [269]:
lr.predict(X[-200:])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3])